backend:
  name: github
  repo: jorsanes/kadmeia-vet-summit   # <-- tu repo
  branch: main
local_backend: true                    # modo local sin OAuth
site_url: https://kadmeia.com
display_url: https://kadmeia.com

media_folder: "public/images/uploads"  # dónde se guardan los archivos en el repo
public_folder: "/images/uploads"       # cómo se referencian en la web
publish_mode: editorial_workflow       # borrador → en revisión → publicado
editor:
  preview: false                       # evita problemas con MDX complejo

collections:
  # BLOG ES
  - name: "blog_es"
    label: "Blog (ES)"
    folder: "src/content/blog/es"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Extracto", name: "excerpt", widget: "text", required: false }
      - { label: "Imagen de portada", name: "cover", widget: "image", required: false }
      - { label: "Idioma", name: "lang", widget: "hidden", default: "es" }
      - { label: "Etiquetas", name: "tags", widget: "list", required: false }
      - { label: "Borrador", name: "draft", widget: "boolean", default: false }
      - { label: "Contenido (MDX)", name: "body", widget: "markdown" }

  # BLOG EN
  - name: "blog_en"
    label: "Blog (EN)"
    folder: "src/content/blog/en"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Cover", name: "cover", widget: "image", required: false }
      - { label: "Lang", name: "lang", widget: "hidden", default: "en" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Content (MDX)", name: "body", widget: "markdown" }

  # CASOS ES
  - name: "cases_es"
    label: "Casos (ES)"
    folder: "src/content/casos/es"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Extracto", name: "excerpt", widget: "text", required: false }
      - { label: "Portada", name: "cover", widget: "image", required: false }
      - { label: "Idioma", name: "lang", widget: "hidden", default: "es" }
      - { label: "Etiquetas", name: "tags", widget: "list", required: false }
      - { label: "Borrador", name: "draft", widget: "boolean", default: false }
      - { label: "Contenido (MDX)", name: "body", widget: "markdown" }

  # CASES EN
  - name: "cases_en"
    label: "Cases (EN)"
    folder: "src/content/casos/en"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Cover", name: "cover", widget: "image", required: false }
      - { label: "Lang", name: "lang", widget: "hidden", default: "en" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Content (MDX)", name: "body", widget: "markdown" }
