backend:
  name: github
  repo: jorsanes/kadmeia-vet-summit   # repo de contenido
  branch: main
  base_url: https://kadmeia-oauth.vercel.app  # tu provider en Vercel
  auth_endpoint: api/auth

# En local, si quieres evitar OAuth, cambia a true:
local_backend: false

site_url: https://www.kadmeia.com
display_url: https://www.kadmeia.com

media_folder: "public/images/uploads"   # dónde se guardan en el repo
public_folder: "/images/uploads"        # cómo se referencian en la web

publish_mode: editorial_workflow        # borrador → revisión → publicado
editor:
  preview: false                        # evita problemas con MDX complejo

collections:
  # BLOG ES
  - name: "blog_es"
    label: "Blog (ES)"
    folder: "src/content/blog/es"
    create: true
    slug: "{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime", format: "YYYY-MM-DD", time_format: false }
      - { label: "Extracto", name: "excerpt", widget: "text", required: false }
      - { label: "Imagen de portada", name: "cove
