name: Lint & Build

on:
  push:
  pull_request:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        with:
          node-version: 20
          cache: pnpm
      - uses: actions/setup-node@v4
        if: ${{ hashFiles('pnpm-lock.yaml') == '' }}
        with:
          node-version: 20
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    env:
      SITE_ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'preview' }}
      SITE_URL: https://kadmeia.com
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        if: ${{ hashFiles('pnpm-lock.yaml') != '' }}
        with:
          node-version: 20
          cache: pnpm
      - uses: actions/setup-node@v4
        if: ${{ hashFiles('pnpm-lock.yaml') == '' }}
        with:
          node-version: 20
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm run build
      - name: Upload sitemap.xml (if generated)
        uses: actions/upload-artifact@v4
        with:
          name: sitemap
          path: public/sitemap.xml
          if-no-files-found: ignore
