name: Lint & Build

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      analyze:
        description: "Run bundle analyzer (pnpm run analyze) and upload stats"
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile=false

      - run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    # En main hacemos 'prod' (genera sitemap), en el resto 'preview' (lo salta)
    env:
      SITE_ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'preview' }}
      SITE_URL: https://kadmeia.com
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile=false

      # Build normal
      - run: pnpm run build

      # (Opcional) Analizar bundle si lo pides al lanzar manualmente
      - name: Bundle analyze
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.analyze == true }}
        run: pnpm run analyze

      - name: Upload bundle stats (if present)
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.analyze == true }}
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: dist/stats.html
          if-no-files-found: ignore

      - name: Upload sitemap.xml (if generated)
        uses: actions/upload-artifact@v4
        with:
          name: sitemap
          path: public/sitemap.xml
          if-no-files-found: ignore

      # En ramas que no sean main, sube el 'dist' para revisar el preview
      - name: Upload dist (preview branches)
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: actions/upload-artifact@v4
        with:
          name: dist-preview
          path: dist
          if-no-files-found: error
